In [1]:
include("twitterJL.jl")

buildSubNetwork (generic function with 1 method)

In [2]:
filename = "data/friends_test"
file = open(filename)
seekend(file)
fLen = Int64(position(file)/4)
seekstart(file)
net = Vector{UInt32}(undef, fLen)
read!(file, net)
close(file)

In [3]:
user1 = userIndexToVector(5, 1000000)

1000000-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [4]:
temp = sparseTransitionMultiplyMV(net, user1, 0.3)

1000000-element Array{Float64,1}:
 0.0008276855754518466
 0.0007811728682010411
 0.0009136583210201255
 0.0011005627111193338
 0.0011531195949160801
 0.0009477748800480211
 0.0010987142318232388
 0.0010670963168435022
 0.0009499795449462418
 0.0011625591579846632
 0.0008400892797532295
 0.001028254407485612 
 0.0010200270878327174
 ⋮                    
 0.0                  
 0.0                  
 0.0                  
 0.0                  
 0.0                  
 0.0                  
 0.0                  
 0.0                  
 0.0                  
 0.0                  
 0.0                  
 0.0                  

In [5]:
for k in 1:100
    temp = normalizeV(sparseTransitionMultiplyMV(net, temp, 0.3))
end

In [6]:
temp = sparseTransitionMultiplyMV(net, temp, 0.3)

1000000-element Array{Float64,1}:
 0.14285714285714282
 0.1428571428571428 
 0.1428571428571428 
 0.1428571428571428 
 0.1428571428571428 
 0.14285714285714282
 0.1428571428571428 
 0.1428571428571428 
 0.1428571428571428 
 0.1428571428571428 
 0.1428571428571428 
 0.1428571428571428 
 0.1428571428571428 
 ⋮                  
 0.0                
 0.0                
 0.0                
 0.0                
 0.0                
 0.0                
 0.0                
 0.0                
 0.0                
 0.0                
 0.0                
 0.0                

In [19]:
out = sparseTransitionPowerIterate_wGS(net, 50, 7, 0.5, 0.00005)

1:
0.9999994209434474
2: 
0.7907247166443386
3: 
0.7614346972196747
4: 
0.7019033640535114
5: 
0.6882276124665156
6: 
0.6766771966352991
7: 
0.6490680136772407


([0.142866 0.0797223 … 0.0219285 0.0454231; 0.142857 -0.0460991 … 0.0952662 -0.0133093; … ; 0.142855 -0.0787792 … -0.411133 0.204717; 0.142863 -0.00104314 … -0.394584 -0.533102], [0.999999, 0.790725, 0.761435, 0.701903, 0.688228, 0.676677, 0.649068])

In [ ]:
out[1]

In [36]:
1/sqrt(k)

0.0012083438570891587

In [61]:
for k = 1:50
    temp[k] = 0.0
end
temp[49] = 1.0

1.0

In [21]:
zeros(length(temp))

1000000-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [17]:
.07*15

1.05

In [9]:
temp[:,1] = testVec

1000000-element Array{Float64,1}:
 0.0015959486547092129 
 0.0004981967199693541 
 0.0004887446383141113 
 0.00010243479279594214
 0.0007613162738317966 
 0.0010041903921251573 
 0.00018622356946049022
 0.0009665422160977886 
 0.0003779028839014108 
 0.0015796276355182224 
 0.0010929087893410024 
 0.0013895527295059902 
 0.0015139984679756555 
 ⋮                     
 0.0005571376977026988 
 0.0009656697220377435 
 0.000632194763788465  
 0.0010547791322293243 
 0.0014566434090950025 
 0.0008288408075230372 
 0.0005200692812308504 
 0.00042672317474899007
 0.0006246449399171918 
 0.001337193594575525  
 0.0010337117076394068 
 0.000506058490979324  

In [11]:
temp[:,2] = sparseAdjacencyMultiplyMV(net, testVec)

1000000-element Array{Float64,1}:
 0.3465393700225263   
 0.12647072747783555  
 0.0986238168254839   
 0.1930524885150142   
 0.18066923801775894  
 0.10773551076299445  
 0.04484642847494889  
 0.5257823546756734   
 0.25001922994031495  
 0.16931802651153313  
 0.04933177207334571  
 0.03790875926317817  
 0.060882717942311614 
 ⋮                    
 0.0032086155583271195
 0.008050454259498931 
 0.006402240242555252 
 0.023741777733234277 
 0.0003515347971505127
 0.010527125577629144 
 6.388194155696666e-5 
 0.01268605208411972  
 0.002543807730505744 
 0.0062140364508322995
 0.0021832048724085853
 0.0002723674897615393

In [7]:
calculateInfluenceVector_v2(net, userIndexToVector(1, 1000000), 0.0, 0.06, 0.000005, 10000)

1000000-element Array{Float64,1}:
 0.05391505632522858  
 1.0325912962635582   
 1.035914010503722    
 1.0361046950216801   
 1.0334209570855952   
 1.0258290595067188   
 1.0366458639091045   
 1.025104861559193    
 1.0202089250850865   
 1.0114288548188544   
 1.0326965122980776   
 1.0181159384089098   
 1.0280868086122046   
 ⋮                    
 0.0007556069911020016
 1.4e-6               
 0.010732565909217279 
 0.002546570505369535 
 0.030930877906054813 
 0.016985010629878016 
 0.06323782966278116  
 0.004588840569724991 
 0.01527028160708594  
 0.0005544251948777817
 0.015573022454542848 
 0.0006049862772295014

In [23]:
function sparseArnoldiIterate(adjacency::Vector{UInt32}, vecLength::Int64, numVecs::Int64)
    out = Array{Float64, 2}(undef, vecLength, numVecs)
    for k = 1:vecLength
        out[k,numVecs] = rand()
    end
    for i = 1:numVecs-1
        out[:,numVecs-i] = normalizeV(sparseAdjacencyMultiplyMV(adjacency, out[:, numVecs-i+1]))
    end
    for m = 2:numVecs
        for n = 1:m
            out[:,m] = addVV(1, out[:,m], -dotVV(out[:,m], out[:,n]), out[:,n])
        end
        out[:,m] = normalizeV(out[:,m])
    end
    return out
end

sparseArnoldiIterate (generic function with 1 method)

In [17]:
out, eigs = sparseArnoldiIterate(net, 1000000, 10)

([0.000976643 0.0021265 … 0.00164556 -0.00131031; 0.000426346 0.00147029 … 0.00125632 -0.000642841; … ; 6.48292e-5 0.000210162 … -0.000190304 -0.000119447; 7.393e-9 8.6654e-8 … 5.75399e-6 0.00160385], [833.132, -50.193, 105.354, 212.381, -123.138, 332.609, -35.6331, 54.3018, -8.56898, -0.0902457])

In [18]:
eigs

10-element Array{Float64,1}:
  833.1317679723005    
  -50.193022692434575  
  105.3542426810932    
  212.38104033767348   
 -123.13755721154455   
  332.6088405624878    
  -35.63312671369444   
   54.30177787387584   
   -8.568980318219314  
   -0.09024565743257543

In [43]:
function sparsePowerIterate(adjacency::Vector{UInt32}, vecLength::Int64, epsilon)
    out = Vector{Float64}(undef, vecLength)
    for k = 1:vecLength
        out[k] = rand()
    end
    out = normalizeV(out)
    epsilon = abs(epsilon)
    e = 10.0*epsilon
    oldL = 10000.0
    lambda = 0.0
    while e > epsilon
        old = out
        out = sparseAdjacencyMultiplyMV(adjacency, old)
        lambda = dotVV(old, out)
        e = abs((lambda-oldL)/(0.5*(lambda+oldL) + .00000000001*rand()))
        oldL = lambda
        out = normalizeV(out)
    end
    return out, lambda
end

sparsePowerIterate (generic function with 1 method)

In [48]:
eigV, lambda = sparsePowerIterate(net, 1000000, 0.0005)

([0.000983526, 0.000428206, 0.0001492, 0.00037672, 0.000132909, 0.000232342, 8.15031e-5, 0.00117985, 0.000688853, 0.000271612  …  3.15091e-5, 0.000127637, 4.01309e-5, 0.00012594, 2.58765e-8, 4.34376e-6, 0.000105441, 6.05605e-5, 6.44586e-5, 7.67043e-9], 832.8124212362585)

In [46]:
function randV(vecLength::Int64)
    out = Vector{Float64}(undef, vecLength)
    for k = 1:vecLength
        out[k] = rand()
    end
    return normalizeV(out)
end

randV (generic function with 1 method)

In [72]:
t = randV(1000000)
t = normalizeV(addVV(1, t, -dotVV(t, eigV), eigV))
println(dotVV(t,eigV))

-2.613393818188224e-14


In [73]:
sparseAdjacencyMultiplyMV(net, t)

1000000-element Array{Float64,1}:
  0.24740009581378888   
  0.08568161841861827   
  0.07745917571974952   
  0.14369628270944088   
  0.17741804101322264   
  0.08442333430429075   
  0.04143369830231565   
  0.43748438044127846   
  0.16680377699059226   
  0.13757690577401493   
  0.03319840720214212   
  0.03806731143622319   
  0.034925179616872484  
  ⋮                     
 -0.00020349269894338255
  0.00715411163130895   
  0.008500214535787693  
  0.007071400194904826  
 -0.0031667835978972823 
 -0.008618387421257154  
  0.0004742843321668175 
  0.008635006037503378  
 -0.010158347234689514  
 -0.001141038435426121  
 -0.005130178348509456  
  0.0008370112982705292 

In [7]:
x = Vector{UInt32}(undef, fLen)
seekstart(file)
read!(file, x)
close(file)

In [7]:
testVec

1000000-element Array{Float64,1}:
 0.7472613912504447 
 0.7734244314984384 
 0.38406015886924383
 0.6371066679109467 
 0.38320285987821845
 0.9411984925750094 
 0.5806627544766021 
 0.15779687868502879
 0.41335339503891944
 0.5998178658426825 
 0.9171882679236778 
 0.5544713728612203 
 0.09148564996379172
 ⋮                  
 0.9502948537734268 
 0.09591517006035577
 0.365508516538505  
 0.2944775319505222 
 0.38275788626986573
 0.40702678807755643
 0.15649631083920124
 0.936355610571693  
 0.6967431422159633 
 0.5387857883049423 
 0.32757932296005965
 0.8256076631889351 

In [11]:
typeof("Hello")

String

In [ ]:
file = open("data/friends_small_indexed", "r")
max = 0
while !eof(file)
    x = read(file, UInt32)
    if x > max
        max = x
    end
end
close(file)
println(string(max, base=10)

In [17]:
function testFunc2(a::Int64)
    return a*a
end

testFunc2 (generic function with 1 method)

In [18]:
p = 5
testFunc2!(p)

UndefVarError: UndefVarError: testFunc2! not defined

In [16]:
p

5

In [75]:
size(Array{Float64,2}(undef, 2,4))

(2, 4)